Name: CI_CD_Pipeline

on:
 push:
 branch:[main]


jobs:
build:
run-on: Ubuntu-latest
steps:
- name: Print Message
 run: echo "hello World, this is a test for CI/CD pipeline!!!!!!!!!!!!!!"
 -name: Cheecking path
 run: pwd
 -name: Checking files
 run: ls -l