name: CI_CD_Pipeline


on:
 push:
  branches: ['main']

permissions:
 contents: read
 packages: write

jobs:
 build_image_and_push:
  runs-on: Ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v4
   - name: Checking path
     run: pwd
   - name: Accessing the file
     run: cd booking && pwd
   - name: Build and push docker image
     run: docker build -t ghcr.io/mahi-oops/booking-app:${{github.run_number}} ./booking
   - name: login to github container registry
     uses: docker/login-action@v2
     with:
      registry: ghcr.io
      username: ${{github.actor}}
      password: ${{secrets.GITHUB_TOKEN}}
   - name: push image to GHCR
     run: docker push ghcr.io/mahi-oops/booking-app:${{github.run_number}} 


 update_manifest_file:
   runs-on: ubuntu-latest 
   needs: build_image_and_push
   steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: clone manifest repo
      run: git clone https://github.com/Mahi-oops/Github_action_CICD_manifest.git
    - name: list files in manifest repo
      run: ls -l 
    - name: Checking path
      run: pwd
    - name: update the manifest file
      run: |
        ls -l
        cd Github_action_CICD_manifest && cd manifest
        pwd
        sed -i "s/build-.*/build-${{github.run_number}}/g" manifest.yml