name: CI_CD_Pipeline

on:
 push:
  branches: ['main']


jobs:
 build:
  runs-on: Ubuntu-latest
  steps:
   - name: checkout code
     uses: actions/checkout@v4
   - name: Checking path
     run: pwd
   - name: Accessing the file
     run: cd booking && pwd
   - name: Build and push docker image
     run: docker build -t ghcr.io/mahi-oops/booking-app:${{github.run_number}} ./booking
   - name: login to github container registry
     uses: docker/login-action@v2
     with:
       username: ${{github.actor}}
       password: ${{github.secrets.github_token}}
   - name: push image to GHCR
     run: docker push ghcr.io/mahi-oops/booking-app:${{github.run_number}} 