name: CI_CD_Pipeline

on:
 push:
  branches: ['main']


jobs:
 build:
  runs-on: Ubuntu-latest
 steps:
   - name: Print Message
     run: echo "hello World, this is a test for CI/CD pipeline!!!!!!!!!!!!!!"
   - name: Checking path
     run: pwd
   - name: Checking files
     run: ls -l